language: node_js
node_js:
   - 0.8


services:
  - couchdb

before_script:
  - npm install grunt@0.3.17 -g
  - npm install

script: "grunt amd test"


notifications:
  email:
    - ryan.ramage@gmail.com
